---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    spec.ingressClassName: "traefik"
spec:
  tls:
  - hosts:
      - "argocd-server.argocd"
    secretName: argocd-secret
  rules:
  - host: "argocd-server.argocd"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port: 
              number: 80
